added wise quotes
akashsara/homebrew_helper pull request #37
Opened 2021-10-30 09:47 UTC by jyotijangid

2021-10-30 13:52 UTC, akashsara requested changes

2021-10-30 13:52 UTC, akashsara commented on config.py
> +    "The only way to learn is to live. - Matt Haig, The Midnight Library
Formatting needs a fix.

2021-10-30 13:52 UTC, akashsara commented on config.py
> +    "I wouldn't mind"
Please remove this.

2021-10-30 13:55 UTC, akashsara commented
Hi, please refer to the review. Also, please add a few more quotes.

2021-10-30 18:45 UTC, akashsara requested changes

2021-10-30 18:45 UTC, akashsara commented on config.py
> +    "“Let us always meet each other with a smile, for the smile is the beginning of love. - Mother Teresa”,
Syntax error

2021-10-31 02:40 UTC, jyotijangid commented on config.py
> +    "“Let us always meet each other with a smile, for the smile is the beginning of love. - Mother Teresa”,
@akashsara removed the syntax error. thankyou

2021-10-31 05:12 UTC, akashsara commented
Please pull the latest changes and resubmit your PR.

2021-10-31 08:41 UTC, jyotijangid commented
branch updated @akashsara

2021-10-31 15:31 UTC, akashsara requested changes

2021-10-31 15:31 UTC, akashsara commented on config.py
> +    "You either die a hero, or live long enough to see yourself become the villain - Harvey Dent",
Duplicate (see line 121)

2021-10-31 15:32 UTC, akashsara commented
Thanks for all the work @jyotijangid! There's just one small issue in that you've added the same quote twice. Once you fix that I'll merge it in.

2021-11-01 00:37 UTC, jyotijangid commented
@akashsara  removed the quote. 
Thankyou for your patience.

2021-11-01 00:38 UTC, merged